/* Turno Andino — archivo histórico de ataques reales y álbum de MITRE ATT&CK.
   Los casos resumen hechos ampliamente documentados en informes públicos; las cifras son aproximadas. */

/* ——— Técnicas de MITRE ATT&CK que se coleccionan en el álbum ——— */
window.ATTACK = [
  { id: "T1566", name: "Phishing", tactic: "Acceso inicial", es: "Mensajes engañosos (correo, SMS, QR) para robar datos o hacer que la víctima ejecute algo.", detect: "Reportes de usuarios, filtros de correo, SPF/DKIM/DMARC y dominios parecidos al tuyo." },
  { id: "T1566.004", name: "Spearphishing Voice", tactic: "Acceso inicial", es: "Engaños por teléfono o notas de voz (vishing), a veces con voces clonadas.", detect: "Verificar siempre por un canal independiente y procesos de doble aprobación." },
  { id: "T1110", name: "Brute Force", tactic: "Acceso a credenciales", es: "Probar muchas contraseñas hasta acertar, incluido el password spraying.", detect: "Muchos eventos 4625 o «Failed password» desde la misma IP en poco tiempo." },
  { id: "T1078", name: "Valid Accounts", tactic: "Acceso inicial y persistencia", es: "Entrar con usuario y clave reales robados: parece un acceso normal.", detect: "Viajes imposibles, horarios raros, equipos nuevos y MFA para todo." },
  { id: "T1136", name: "Create Account", tactic: "Persistencia", es: "Crear una cuenta nueva para poder volver a entrar.", detect: "Alertas de cuentas nuevas, sobre todo con privilegios (UID 0, administradores)." },
  { id: "T1053.003", name: "Scheduled Task/Job: Cron", tactic: "Persistencia y ejecución", es: "Dejar una tarea programada que ejecuta el malware una y otra vez.", detect: "Revisar crontab y los logs de cron; scripts en carpetas como /tmp." },
  { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Acceso inicial", es: "Aprovechar una falla de una aplicación expuesta a internet (inyección SQL, Log4Shell, Struts).", detect: "WAF, logs web con patrones de ataque y parches a tiempo." },
  { id: "T1571", name: "Non-Standard Port", tactic: "Mando y control", es: "Comunicarse con el atacante por puertos poco comunes, como el 4444.", detect: "Reglas de salida en el firewall y alertas por puertos inusuales." },
  { id: "T1071.004", name: "Application Layer Protocol: DNS", tactic: "Mando y control", es: "Esconder comandos o datos dentro de consultas DNS.", detect: "Consultas muy largas, aleatorias o de tipo TXT en exceso." },
  { id: "T1114.003", name: "Email Forwarding Rule", tactic: "Recolección", es: "Crear reglas que reenvían el correo de la víctima al atacante.", detect: "Alertas de reglas nuevas con reenvío a dominios externos." },
  { id: "T1059.001", name: "PowerShell", tactic: "Ejecución", es: "Usar PowerShell para ejecutar código, muchas veces codificado.", detect: "Procesos padre raros (Word → PowerShell) y el parámetro -enc." },
  { id: "T1204.002", name: "User Execution: Malicious File", tactic: "Ejecución", es: "Lograr que la víctima abra un archivo malicioso, como una factura con macros.", detect: "Bloquear macros de internet y vigilar lo que abren los documentos." },
  { id: "T1486", name: "Data Encrypted for Impact", tactic: "Impacto", es: "Cifrar los datos para pedir un rescate: el ransomware.", detect: "Muchos archivos cambiando de golpe; respaldos desconectados para recuperar." },
  { id: "T1046", name: "Network Service Discovery", tactic: "Descubrimiento", es: "Escanear para saber qué servicios hay en la red (lo que también haces tú, con permiso).", detect: "Una IP tocando muchos puertos en segundos." },
  { id: "T1210", name: "Exploitation of Remote Services", tactic: "Movimiento lateral", es: "Saltar entre equipos aprovechando fallas de servicios de red, como EternalBlue en SMB.", detect: "Parchar, apagar SMBv1 y segmentar la red." },
  { id: "T1195.002", name: "Compromise Software Supply Chain", tactic: "Acceso inicial", es: "Meter código malicioso en el software de un proveedor para llegar a sus clientes.", detect: "Vigilar el comportamiento del software de terceros, no solo confiar en su firma." },
  { id: "T1133", name: "External Remote Services", tactic: "Acceso inicial", es: "Entrar por servicios de acceso remoto expuestos, como una VPN o RDP.", detect: "MFA obligatorio en todo acceso remoto y apagar cuentas viejas." },
  { id: "T1199", name: "Trusted Relationship", tactic: "Acceso inicial", es: "Entrar a través de un proveedor que ya tiene acceso a la red de la víctima.", detect: "Accesos de terceros limitados, segmentados y con MFA." },
  { id: "T1552.005", name: "Cloud Instance Metadata API", tactic: "Acceso a credenciales", es: "Robar credenciales temporales de la nube pidiéndoselas al servicio de metadatos del servidor.", detect: "Usar IMDSv2 en AWS, bloquear SSRF y vigilar el uso de esas credenciales." },
  { id: "T1530", name: "Data from Cloud Storage", tactic: "Recolección", es: "Sacar datos de buckets o almacenamiento en la nube.", detect: "Registros de acceso a los buckets y alertas por descargas masivas." },
];

/* ——— Casos reales. Se desbloquea uno cada 3 turnos. ——— */
window.CASES = [
  { id: "bangladesh", year: 2016, title: "El robo al Banco de Bangladesh", sector: "Banca", techs: ["T1078", "T1566"],
    story: [
      "En febrero de 2016, unos atacantes que llevaban meses dentro de la red del Banco Central de Bangladesh usaron credenciales reales de SWIFT para enviar 35 órdenes de pago falsas a la Reserva Federal de Nueva York, por casi 1.000 millones de dólares.",
      "La mayoría se frenó, en parte por un error de ortografía («fandation» en vez de «foundation») que levantó sospechas. Aun así, salieron 101 millones: 20 se recuperaron desde Sri Lanka, pero 81 terminaron en casinos de Filipinas y casi no se recuperaron.",
      "El malware alteraba los reportes y la impresora de confirmaciones para esconder las transferencias. EE. UU. atribuyó el ataque al grupo Lazarus, vinculado a Corea del Norte.",
    ],
    timeline: ["Acceso a la red del banco meses antes", "Robo de credenciales del sistema SWIFT", "35 órdenes de pago falsas un viernes por la noche", "Malware oculta las confirmaciones impresas", "81 millones salen hacia casinos de Filipinas"],
    lessons: ["Los sistemas de pagos críticos deben estar aislados y vigilados de cerca.", "Las transferencias grandes necesitan verificaciones fuera de banda.", "SWIFT creó después su marco de controles obligatorios (CSP)."],
    quiz: [
      { q: "¿Qué usaron los atacantes para enviar las órdenes de pago?", a: ["Credenciales reales del sistema SWIFT", "Una falla en el sitio web del banco", "Billetes falsos en un cajero"], c: 0, w: "Con credenciales válidas, las órdenes parecían legítimas (T1078)." },
      { q: "¿Qué ayudó a frenar parte del robo?", a: ["Un antivirus actualizado", "Un error de ortografía en una orden", "Un apagón en Nueva York"], c: 1, w: "«Fandation» en lugar de «foundation» hizo que un banco intermediario revisara la orden." },
      { q: "¿Qué hacía el malware para esconder el robo?", a: ["Cifraba todos los discos del banco", "Enviaba correos a los clientes", "Alteraba los reportes y las confirmaciones impresas"], c: 2, w: "Así, el personal no veía las transferencias hasta que fue tarde." },
    ] },
  { id: "wannacry", year: 2017, title: "WannaCry", sector: "Salud y todos los sectores", techs: ["T1210", "T1486"],
    story: [
      "El 12 de mayo de 2017 un ransomware llamado WannaCry infectó más de 200.000 computadores en unos 150 países en pocas horas. Hospitales del sistema de salud británico (NHS) tuvieron que cancelar citas y desviar ambulancias.",
      "No necesitaba que nadie hiciera clic: se propagaba solo por la red usando EternalBlue, una falla de SMBv1 en Windows. Microsoft la había corregido en marzo con el parche MS17-010, dos meses antes; los equipos afectados no lo tenían.",
      "Un investigador, Marcus Hutchins, frenó la propagación al registrar un dominio que el malware consultaba como «interruptor de apagado». EE. UU. y el Reino Unido atribuyeron el ataque a Corea del Norte.",
    ],
    timeline: ["Marzo: Microsoft publica el parche MS17-010", "12 de mayo: primeros equipos cifrados", "El gusano se propaga solo por SMB", "Se registra el dominio que lo detiene", "Miles de equipos sin parche quedan dañados"],
    lessons: ["Parchar a tiempo, sobre todo fallas que se explotan por red.", "Apagar protocolos viejos como SMBv1.", "Segmentar la red para que un gusano no llegue a todo."],
    quiz: [
      { q: "¿Cómo se propagaba WannaCry?", a: ["Solo con memorias USB", "Por la red, usando una falla de SMBv1", "Por mensajes de texto"], c: 1, w: "Era un gusano: saltaba de equipo en equipo sin ayuda del usuario (T1210)." },
      { q: "¿Existía un parche antes del ataque?", a: ["Sí, Microsoft lo publicó dos meses antes", "No, era un día cero", "Sí, pero solo para Linux"], c: 0, w: "MS17-010 salió en marzo de 2017. El problema fue no aplicarlo." },
      { q: "¿Qué detuvo la propagación?", a: ["Pagar el rescate", "Apagar internet en Europa", "Registrar un dominio que funcionaba como interruptor"], c: 2, w: "El malware revisaba ese dominio; al existir, dejaba de propagarse." },
    ] },
  { id: "equifax", year: 2017, title: "Equifax", sector: "Buró de crédito", techs: ["T1190"],
    story: [
      "En marzo de 2017 se publicó una falla crítica en Apache Struts (CVE-2017-5638), con su parche. Equifax, una de las centrales de riesgo más grandes de EE. UU., no lo aplicó en su portal de reclamos de clientes.",
      "A mediados de mayo los atacantes entraron por esa falla y durante unos dos meses sacaron datos personales de unos 147 millones de personas: nombres, números de seguridad social y fechas de nacimiento.",
      "Tardaron en notarlo porque un certificado vencido en un equipo de inspección de tráfico hizo que ese tráfico no se revisara durante meses. El acuerdo con las autoridades llegó a unos 700 millones de dólares.",
    ],
    timeline: ["Marzo: se publica la falla de Struts y su parche", "Equifax no parcha el portal de reclamos", "Mayo: los atacantes entran por la falla", "Dos meses sacando datos sin ser detectados", "Julio: renuevan un certificado y ven el tráfico raro"],
    lessons: ["Tener inventario de qué software usa cada aplicación.", "Parchar primero lo expuesto a internet.", "Vigilar que las herramientas de monitoreo funcionen (un certificado vencido las dejó ciegas)."],
    quiz: [
      { q: "¿Por dónde entraron los atacantes?", a: ["Por una falla sin parchar en un portal web público", "Por un correo de phishing al presidente", "Por un cajero automático"], c: 0, w: "Explotaron Apache Struts en una aplicación expuesta a internet (T1190)." },
      { q: "¿Por qué tardaron tanto en detectarlo?", a: ["No tenían ningún firewall", "Un certificado vencido dejó sin inspeccionar ese tráfico", "Los atacantes borraron internet"], c: 1, w: "Cuando renovaron el certificado, el tráfico sospechoso apareció." },
      { q: "¿Cuál fue la lección principal?", a: ["Pagar los rescates rápido", "No usar software libre nunca", "Parchar a tiempo lo que está expuesto a internet"], c: 2, w: "El parche existía desde marzo; el ataque empezó en mayo." },
    ] },
  { id: "target", year: 2013, title: "Target y el proveedor de aire acondicionado", sector: "Comercio", techs: ["T1199", "T1566"],
    story: [
      "En noviembre de 2013, en plena temporada de compras, los atacantes entraron a la red de Target, una gran cadena de tiendas de EE. UU., usando credenciales robadas a un pequeño proveedor de aire acondicionado que tenía acceso a un portal del cliente.",
      "Desde ahí se movieron hasta las cajas registradoras e instalaron malware que copiaba los datos de las tarjetas al pasarlas. Se robaron datos de unos 40 millones de tarjetas y datos personales de unos 70 millones de clientes.",
      "Las herramientas de seguridad de Target sí generaron alertas, pero no se actuó a tiempo. El costo total superó los 200 millones de dólares y renunciaron altos directivos.",
    ],
    timeline: ["Phishing al proveedor de aire acondicionado", "Uso de sus credenciales para entrar a Target", "Movimiento hasta las cajas registradoras", "Malware copia las tarjetas al pagar", "Las alertas no se atienden a tiempo"],
    lessons: ["Los proveedores con acceso son parte de tu superficie de ataque.", "Segmentar: un proveedor de clima no debería poder llegar a las cajas.", "Una alerta que nadie atiende no protege a nadie."],
    quiz: [
      { q: "¿Cómo entraron los atacantes a Target?", a: ["Con credenciales robadas a un proveedor", "Por una falla en el sitio web", "Sobornando a un cajero"], c: 0, w: "Relación de confianza (T1199): el proveedor tenía acceso a la red." },
      { q: "¿Qué falló en la red de Target?", a: ["No tenían internet", "El proveedor pudo llegar hasta las cajas registradoras", "Usaban demasiado cifrado"], c: 1, w: "Faltó segmentación entre sistemas de terceros y el entorno de tarjetas." },
      { q: "¿Qué pasó con las alertas de seguridad?", a: ["No existían", "Bloquearon el ataque", "Se generaron, pero no se actuó a tiempo"], c: 2, w: "Detectar sin responder es casi igual a no detectar." },
    ] },
  { id: "capitalone", year: 2019, title: "Capital One en la nube", sector: "Banca", techs: ["T1552.005", "T1530"],
    story: [
      "En 2019, una persona aprovechó un firewall de aplicaciones web (WAF) mal configurado en la infraestructura de Capital One en AWS. Con una falla SSRF, hizo que el servidor le pidiera sus propias credenciales temporales al servicio de metadatos de la nube.",
      "Ese rol tenía más permisos de los necesarios: con él pudo listar y descargar buckets S3 con solicitudes de tarjetas de crédito de unos 106 millones de personas en EE. UU. y Canadá.",
      "El banco se enteró porque alguien encontró los datos publicados en GitHub y le avisó. El regulador multó después a Capital One con 80 millones de dólares.",
    ],
    timeline: ["WAF mal configurado permite SSRF", "El servidor entrega credenciales de su rol", "El rol tenía demasiados permisos", "Descarga de buckets con solicitudes de tarjeta", "Un aviso externo, por datos en GitHub, alerta al banco"],
    lessons: ["Mínimo privilegio también para los roles de la nube.", "Proteger el servicio de metadatos (IMDSv2 en AWS).", "Vigilar descargas masivas de los buckets."],
    quiz: [
      { q: "¿Qué tipo de falla abrió la puerta?", a: ["Un SSRF por un WAF mal configurado", "Un correo de phishing", "Una contraseña escrita en un papel"], c: 0, w: "El SSRF hizo que el servidor consultara sus propias credenciales (T1552.005)." },
      { q: "¿Qué empeoró el daño?", a: ["El bucket estaba cifrado", "El rol tenía más permisos de los necesarios", "Tenían demasiado MFA"], c: 1, w: "Con mínimo privilegio, esas credenciales no habrían podido leer esos buckets." },
      { q: "¿Qué control ayuda contra este robo de credenciales?", a: ["Desactivar el antivirus", "Usar solo HTTP", "Proteger el servicio de metadatos (IMDSv2)"], c: 2, w: "IMDSv2 exige un token de sesión que un SSRF simple no consigue." },
    ] },
  { id: "solarwinds", year: 2020, title: "SolarWinds", sector: "Software y gobierno", techs: ["T1195.002"],
    story: [
      "Los atacantes entraron a SolarWinds, empresa que fabrica Orion, un software de monitoreo muy usado, y metieron código malicioso en sus actualizaciones oficiales, firmadas por la propia empresa.",
      "Unas 18.000 organizaciones descargaron la actualización. En un grupo mucho más pequeño, incluidas agencias del gobierno de EE. UU., los atacantes usaron esa puerta para espiar durante meses.",
      "Lo descubrió en diciembre de 2020 la empresa de seguridad FireEye, que también había sido atacada. EE. UU. lo atribuyó al servicio de inteligencia exterior de Rusia.",
    ],
    timeline: ["Entrada a la red de desarrollo de SolarWinds", "Código malicioso dentro de las actualizaciones de Orion", "Miles de clientes instalan la actualización firmada", "Espionaje selectivo durante meses", "FireEye lo descubre en diciembre de 2020"],
    lessons: ["Un proveedor de confianza también puede ser la puerta de entrada.", "Vigilar el comportamiento del software, no solo que esté firmado.", "Proteger el proceso con el que se construye el software."],
    quiz: [
      { q: "¿Cómo llegó el malware a los clientes?", a: ["Dentro de una actualización oficial y firmada", "Por correos de phishing masivos", "Por memorias USB en las oficinas"], c: 0, w: "Compromiso de la cadena de suministro de software (T1195.002)." },
      { q: "¿Por qué fue tan difícil de notar?", a: ["Porque no tenía ningún efecto", "Porque venía firmado por un proveedor de confianza", "Porque solo afectaba a Linux"], c: 1, w: "Todo parecía legítimo: el software y la firma eran del proveedor real." },
      { q: "¿Qué lección deja para tu empresa?", a: ["Nunca actualizar el software", "Confiar ciegamente en los proveedores", "Vigilar también lo que hace el software de terceros"], c: 2, w: "La confianza se verifica: comportamiento, permisos mínimos y segmentación." },
    ] },
  { id: "colonial", year: 2021, title: "Colonial Pipeline", sector: "Energía", techs: ["T1133", "T1078", "T1486"],
    story: [
      "En mayo de 2021, el grupo de ransomware DarkSide atacó a Colonial Pipeline, el oleoducto que lleva cerca de la mitad del combustible de la costa este de EE. UU. La empresa detuvo el oleoducto unos seis días y hubo filas y escasez en gasolineras.",
      "Según la propia empresa ante el Congreso, los atacantes entraron con la contraseña de una cuenta de VPN vieja que ya no se usaba y que no tenía MFA.",
      "Colonial pagó unos 4,4 millones de dólares en bitcoin. El Departamento de Justicia recuperó después cerca de la mitad.",
    ],
    timeline: ["Contraseña de una VPN antigua filtrada", "Entrada sin MFA a la red", "Robo de datos y cifrado de sistemas", "La empresa detiene el oleoducto", "Pago del rescate y recuperación parcial"],
    lessons: ["MFA en todo acceso remoto, sin excepción.", "Desactivar las cuentas que ya no se usan.", "Tener planes para seguir operando aunque caiga TI."],
    quiz: [
      { q: "¿Por dónde entraron los atacantes?", a: ["Por una cuenta de VPN vieja sin MFA", "Por un satélite", "Por un empleado que vendió su clave en persona"], c: 0, w: "Servicios remotos externos (T1133) con una cuenta válida (T1078)." },
      { q: "¿Qué control habría hecho mucho más difícil la entrada?", a: ["Un fondo de pantalla nuevo", "MFA en el acceso remoto", "Más impresoras"], c: 1, w: "Con MFA, la contraseña filtrada no habría bastado." },
      { q: "¿Qué otra lección deja?", a: ["Pagar siempre el rescate", "Apagar los respaldos", "Desactivar las cuentas que ya no se usan"], c: 2, w: "Esa cuenta de VPN ya no se necesitaba y seguía activa." },
    ] },
];

/* ——— Comandos reales: elige el que responde la pregunta y mira su salida. ——— */
window.CMDS = [
  { os: "Linux", tags: ["MDE", "GRU"], q: "¿Quiénes iniciaron sesión hace poco en el servidor rpt-01?",
    opts: ["last -n 5", "ls -la /home", "ps aux", "df -h"], c: 0,
    out: ["lrojas   pts/0   10.20.5.14    Mon Sep 21 07:58   still logged in", "backup   pts/1   103.77.12.9   Sun Sep 20 02:14 - 03:02  (00:48)", "deploy   pts/0   10.20.8.2     Sat Sep 19 18:30 - 18:41  (00:11)", "", "wtmp begins Tue Sep  1 00:00:01 2026"],
    why: "last lee el registro de sesiones (wtmp). Ojo: la cuenta backup entró a las 2 a. m. desde una IP externa." },
  { os: "Linux", tags: ["MDE", "UIO"], q: "¿Qué puertos están esperando conexiones en este servidor?",
    opts: ["cat /etc/hosts", "ss -tulpn", "ping localhost", "uname -a"], c: 1,
    out: ["Netid State  Local Address:Port  Process", "tcp   LISTEN 0.0.0.0:22          users:((\"sshd\",pid=812))", "tcp   LISTEN 127.0.0.1:5432      users:((\"postgres\",pid=940))", "tcp   LISTEN 0.0.0.0:4444        users:((\"nc\",pid=3107))"],
    why: "ss -tulpn lista puertos TCP/UDP a la escucha con su proceso. Un nc escuchando en el 4444 es muy sospechoso." },
  { os: "Linux", tags: ["MDE"], q: "¿Qué procesos consumen más CPU ahora mismo?",
    opts: ["ls -lh /var/log", "who", "ps aux --sort=-%cpu | head -5", "history"], c: 2,
    out: ["USER    PID  %CPU %MEM COMMAND", "backup 3190  98.7  2.1 /tmp/.x11-cache/minero.sh", "root    812   0.3  0.1 /usr/sbin/sshd -D", "postgres 940 0.2  1.4 postgres"],
    why: "ps ordena los procesos por CPU. Un script en /tmp usando el 98 % suele ser un minero de criptomonedas." },
  { os: "Linux", tags: ["MDE", "GRU"], q: "¿Qué tareas programadas tiene el usuario backup?",
    opts: ["sudo crontab -l -u backup", "sudo passwd backup", "sudo userdel backup", "sudo id backup"], c: 0,
    out: ["# m h dom mon dow command", "0 1 * * * /opt/backup/nightly.sh", "*/5 * * * * /tmp/.x11-cache/minero.sh"],
    why: "crontab -l -u muestra las tareas de ese usuario. La segunda línea ejecuta el minero cada 5 minutos: persistencia." },
  { os: "Linux", tags: ["BOG", "MDE"], q: "¿La ISO que descargaste coincide con el hash publicado?",
    opts: ["md5 --check-all", "sha256sum ubuntu.iso", "hash -r ubuntu.iso", "gpg --list-keys"], c: 1,
    out: ["3b0c1f56e8a2d4c9b7f1e0a6d5c4b3a2918f7e6d5c4b3a2918f7e6d5c4b3a291  ubuntu.iso"],
    why: "sha256sum calcula el hash SHA-256; se compara carácter por carácter con el publicado en el sitio oficial." },
  { os: "Linux", tags: ["MDE", "GRU"], q: "¿Qué archivos de /etc cambiaron en las últimas 24 horas?",
    opts: ["ls /etc | sort", "grep -r cambio /etc", "find /etc -mtime -1", "du -sh /etc"], c: 2,
    out: ["/etc/passwd", "/etc/shadow", "/etc/ssh/sshd_config"],
    why: "find -mtime -1 lista lo modificado hace menos de un día. Que cambien passwd, shadow y sshd_config de golpe merece investigarse." },
  { os: "Windows", tags: ["BOG", "GRU"], q: "¿Cuáles fueron los últimos 5 inicios de sesión fallidos en este Windows?",
    opts: ["Get-WinEvent -FilterHashtable @{LogName='Security'; Id=4625} -MaxEvents 5", "Get-WinEvent -FilterHashtable @{LogName='Security'; Id=4624} -MaxEvents 5", "Get-WinEvent -FilterHashtable @{LogName='System'; Id=4625} -MaxEvents 500"], c: 0,
    out: ["TimeCreated            Id  Message", "21/09/2026 08:02:11  4625  An account failed to log on. Account: admin", "21/09/2026 08:02:10  4625  An account failed to log on. Account: admin", "21/09/2026 08:02:09  4625  An account failed to log on. Account: admin"],
    why: "Los fallos (4625) están en el registro Security, no en System. El 4624 son los inicios exitosos." },
  { os: "Windows", tags: ["BOG"], q: "¿Qué conexiones de red tiene abiertas este equipo ahora?",
    opts: ["Get-NetTCPConnection -State Established", "Get-LocalUser | Format-Table", "Get-Service | Where Status -eq Running", "Get-ChildItem C:\\Users"], c: 0,
    out: ["LocalAddress  LocalPort RemoteAddress    RemotePort State       OwningProcess", "10.20.6.77    51544     185.220.101.9    4444       Established 6120", "10.20.6.77    51210     142.250.78.4     443        Established 4388"],
    why: "Get-NetTCPConnection muestra las conexiones y el proceso dueño. La del puerto 4444 hacia afuera es la que hay que investigar." },
];
